"""crear_columna_estado_lead

Revision ID: 337ec13a07eb
Revises: c6193c348384
Create Date: 2026-07-25 00:32:29.226819

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '337ec13a07eb'
down_revision: Union[str, Sequence[str], None] = 'c6193c348384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('estado_lead', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'estado_lead')
    # ### end Alembic commands ###
