"""creacion_chat_id_telegram_en_el_esquema_de_la_base_de_datos

Revision ID: 6cb4bf5ab92f
Revises: d90a56757859
Create Date: 2026-07-27 00:10:58.527007

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb4bf5ab92f'
down_revision: Union[str, Sequence[str], None] = 'd90a56757859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asesores', sa.Column('chat_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asesores', 'chat_id')
    # ### end Alembic commands ###
